networks:
  toubeelib.net:
    driver: bridge
services:

  # service api.toubeelib : api pour la prise de rdv
  #
  api.toubeelib:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    container_name: api_toubeelib

    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
      - ./sql:/var/sql
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

    # service toubeelib.db : base de données postgresql
  toubeelib.auth.db:
    image: 'postgres:latest'
    env_file: ./toubeelibauthdb.env
    ports:
      - '5433:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./app/sql:/var/sql'

  toubeelib.db:
    image: 'postgres:latest'
    env_file: ./toubeelibdb.env
    ports:
      - '5432:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./app/sql:/var/sql'
  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - toubeelib.net

